eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: "aHVtbWVTZWNyZXRLZXlGb3JJc0pXVFNvbWVHZW5lcmF0ZWRLZXk="

server:
  port: 8082
spring:
  application:
    name: product-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/proj-e-commerce_product?reWriteBatchedInserts=true&preferQueryMode=simple&tcpKeepAlive=true&socketTimeout=30&connectTimeout=30"
    username: postgres
    password: "Bangsat@123"
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

management:
  tracing:
    sampling:
      probability: 1.0